[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bip-project-services"
version = "0.1.0"
description = "BIP project services organized in src layout"
requires-python = ">=3.13"
dependencies = [
	"paho-mqtt",
	"pyserial",
	"numpy",
	"PyYAML",
	"opencv-python",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
