
# MQTT configuration
mqtt:
  host: ed1fe6fe.ala.eu-central-1.emqxsl.com
  port: 8883
  username: crane-pi-1
  password: crane-pi
  ca_cert_path: emqxsl-ca.crt
  base_topic: bip/mqtt-lab
  qos: 2
  keepalive: 60

# Camera configuration
cam:
  cam_id: 1