
# MQTT configuration
mqtt:
  host: ed1fe6fe.ala.eu-central-1.emqxsl.com
  port: 8883
  username: crane-pi-1
  password: crane-pi
  ca_cert_path: emqxsl-ca.crt
  base_topic: bip/mqtt-lab
  qos: 2
  keepalive: 60

# Camera configuration
cam:
  # Windows
  cam_id: 1
  # Linux
  cam_name: "/dev/video0"
  # Optional: set false to force headless mode even if a display is available.
  preview: true